export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SAVE_TRANSLATIONS = 'SAVE_TRANSLATIONS';
export const SAVE_TRANSLATION_TO_LOCAL = 'SAVE_TRANSLATION_TO_LOCAL';
export const DELETE_TRANSLATION = 'DELETE_TRANSLATION';